server:
  port: 8081

spring:
  application:
    name: welove-service #服务名称

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/popular?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: admin
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false


# mybatis相关配置
mybatis-plus:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    use-column-label: true
    ###############这个配置结合上面spring一个配置解决mybatis字段返回map的时候当结果为null的时候要返回字段
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/**/*.xml

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#生产环境关闭swagger
swagger:
  enabled: true
